# Default configuration file for a Stock trading strategy
ticker: 'AAPL'
start_date: '2022-01-01'
end_date: '2023-01-01'
short_window: 20
long_window: 50
initial_capital: 100000
commission: 0.001
slippage: 0.001
risk_free_rate: 0.01
position_size: 100
stop_loss: 0.05
take_profit: 0.10
rebalance_frequency: 'monthly'
data_source: 'yahoo'
data_frequency: 'daily'
data_columns:
  - 'Open'
  - 'High'
  - 'Low'
  - 'Close'
  - 'Volume'
indicators:
  - name: 'SMA'
    period: 20
    type: 'simple'
  - name: 'EMA'
    period: 50
    type: 'exponential'
  - name: 'RSI'
    period: 14
    overbought: 70
    oversold: 30
  - name: 'MACD'
    fast_period: 12
    slow_period: 26
    signal_period: 9
  - name: 'Bollinger Bands'
    period: 20
    std_dev: 2
  - name: 'ATR'
    period: 14
  - name: 'Stochastic Oscillator'
    fast_k_period: 14
    slow_k_period: 3
    slow_d_period: 3
  - name: 'ADX'
    period: 14
    threshold: 25
  - name: 'CCI'
    period: 20
    threshold: 100
  - name: 'Williams %R'
    period: 14
    overbought: -20
    oversold: -80
  - name: 'Fibonacci Retracement'
    levels:
      - 0.0
      - 0.236
      - 0.382
      - 0.618
      - 1.0
  - name: 'Volume Weighted Average Price'
    period: 20
  - name: 'Ichimoku Cloud'
    tenkan_sen_period: 9
    kijun_sen_period: 26
    senkou_span_b_period: 52
    displacement: 26
  - name: 'Parabolic SAR'
    acceleration: 0.02
    maximum: 0.2
  - name: 'Pivot Points'
    period: 'daily'
    levels:
      - 'R1'
      - 'R2'
      - 'R3'
      - 'S1'
      - 'S2'
      - 'S3'
  - name: 'Donchian Channel'
    period: 20
  - name: 'Keltner Channel'
    period: 20
    atr_multiplier: 1.5
  - name: 'Average True Range'
    period: 14
  - name: 'Chaikin Money Flow'
    period: 20
  - name: 'Accumulation/Distribution Line'
    period: 20
  - name: 'On-Balance Volume'
    period: 20
  - name: 'Money Flow Index'
    period: 14
    overbought: 80
    oversold: 20
  - name: 'Elder Ray Index'
    period: 13
  - name: 'Market Facilitation Index'
    period: 1
  - name: 'Trix'
    period: 15
    signal_period: 9
  - name: 'Aroon Indicator'
    period: 14
  - name: 'Ultimate Oscillator'
    period1: 7
    period2: 14
    period3: 28
  - name: 'Price Rate of Change'
    period: 14
    threshold: 0.05
  - name: 'BOP'
    period: 14
  - name: 'Vortex Indicator'
    period: 14
  - name: 'DMI'
    period: 14
    threshold: 20
  - name: 'Coppock Curve'
    period1: 14
    period2: 11
    period3: 10
  - name: 'Zig Zag'
    deviation: 5
    depth: 14
  - name: 'Heikin Ashi'
    period: 14
  - name: 'Renko'
    brick_size: 1
  - name: 'Point and Figure'
    box_size: 1
    reversal: 3
  - name: 'Range Bars'
    range: 1